### ISSUE TITLE
Override mock response for path

### ISSUE THREAD

**Issue by xpureTobias** [depoon/SwiftLocalhost#11]
Hi,
I know this has been discussed before. We have the case where we need to override the mock response at runtime. The Criollo server stores the configured routes in an array. Whenever a request comes in it would return the first match. 

I was able to adjust the `LocalhostServer.swift` to make it work. Please let me know if you would like me to open a PR. It's probably not the most clean solution but works for our needs and doesn't break anything else afaik.

**Comment by depoon** [comment]
@xpureTobias   Sorry for the long wait.
Kindly help review the latest PR. https://github.com/depoon/SwiftLocalhost/pull/14

use the following in your podfile
```
pod 'SwiftLocalhost', :git => 'https://github.com/depoon/SwiftLocalhost.git', :branch => 'multiple-response-per-path-route'
```

I will merge the branch in 1 week time, or earlier if you can give me your feedback.

**Comment by depoon** [comment]
Hi @xpureTobias ,

I've merged the feature to allow developers to mock multiple response for the same path. Note that this requires you to take note of the order of requests being fired and match the respective mock responses in the same order
