### ISSUE TITLE
How to mock the same path but data in request's body are different ?

### ISSUE THREAD

**Issue by up1** [depoon/SwiftLocalhost#12]
How to mock the same path but data in request's body are different ?

**Comment by depoon** [comment]
@up1  Sorry for the long wait.
Kindly help review the latest PR. https://github.com/depoon/SwiftLocalhost/pull/14

use the following in your podfile
```
pod 'SwiftLocalhost', :git => 'https://github.com/depoon/SwiftLocalhost.git', :branch => 'multiple-response-per-path-route'
```

I will merge the branch in 1 week time, or earlier if you can give me your feedback.

**Comment by depoon** [comment]
Hi @up1,

I've merged the feature to allow developers to mock multiple response for the same path. Note that this requires you to take note of the order of requests being fired and match the respective mock responses in the same order.

Meanwhile i will close this issue. Thanks
