### ISSUE TITLE
Identical requests in one test

### ISSUE THREAD

**Issue by manyakin** [depoon/SwiftLocalhost#8]
Good day. In my test, I use two identical requests with the same path, but with a different body. And the application always uses the first request, and the second is ignored. Is it possible to use requests in the order of their initialization, or in some other way?

**Comment by depoon** [comment]
Presently this library does not have this feature.
You will need to redefine the requests in between your test steps to override the mock response.

Meanwhile ll try to build something for you

**Comment by xpureTobias** [comment]
Hey, is there some news on this question? We basically have a similar case where we call the same endpoint twice and need different responses within one UI test. 

I check the Criollo Server and saw that the `routes` are stored in a readonly array. There probably is no way to remove a route. To find a solution I was thinking it would be nice to have the option to pass an alias for a certain route. 
So e.g. `/currentStatus` with alias `initial` becomes internally `/currentStatus/initial`.

**Comment by depoon** [comment]
@xpureTobias Sorry for the long wait.
Kindly help review the latest PR. https://github.com/depoon/SwiftLocalhost/pull/14

use the following in your podfile
```
pod 'SwiftLocalhost', :git => 'https://github.com/depoon/SwiftLocalhost.git', :branch => 'multiple-response-per-path-route'
```

I will merge the branch in 1 week time, or earlier if you can give me your feedback.

**Comment by depoon** [comment]
Hi @manyakin @xpureTobias ,

I've merged the feature to allow developers to mock multiple response for the same path. Note that this requires you to take note of the order of requests being fired and match the respective mock responses in the same order
